### ISSUE TITLE
Specify more than one coordinates in the filter

### ISSUE THREAD

**Issue by NirutaDhimal** [pydicom/deid#230] opened 2022-10-01 08:44 UTC
I am trying to remove clean pixels of 2 -3 coordinates of a dicom file. How do I specify it in the filter ?
[
![err2](https://user-images.githubusercontent.com/58328226/193401096-f88c1d37-c1c2-401d-9ab2-d35d4245aa3b.png)
This is my filter But I want to clean pixels on bounding box 4,462,23,102. How do I add this in filter?

**Comment by vsoch** [comment] 2022-10-01 08:48
Here is an example of an entry with two coordinates: https://github.com/pydicom/deid/blob/master/deid/data/deid.dicom#L301-L308

**Comment by NirutaDhimal** [comment] 2022-10-01 08:56
I tried that but It's not working. Only the First coordinates were removed.

**Comment by vsoch** [comment] 2022-10-01 12:39
That's a bug then! Are you able to share some dummy data so I can use for a debuggig/test case?

**Comment by vsoch** [comment] 2022-10-01 12:42
Actually I have a good test case already! I should be able to work on this and propose a fix today - stay tuned!

**Comment by NirutaDhimal** [comment] 2022-10-01 14:13
I don't have any dummy data. Sorry for that. Thanks

**Comment by vsoch** [comment] 2022-10-01 17:51
@NirutaDhimal I tested the syntax with multiple coordinates and it appears to work as I'd expect (both sets show up):

```
In [1]: results['results']
Out[1]: 
[{'reason': 'and Manufacturer contains Philips Modality contains US ImageType contains Cardiology',
  'group': 'graylist',
  'coordinates': [[0, '0,0,1024,23'], [0, '0,0,1024,23']]}] # notice there are two here
```
I think very likely the issue is that you either have a bug in the bounding box you are asking for, or a "contains" statement that doesn't apply to your image. It's hard to debug beyond that without seeing your data. However, the format for the coordinates that I showed above is correct.

**Comment by NirutaDhimal** [comment] 2022-10-06 02:10
@vsoch I printed client.detect() result and both set shows up in the coordinates. But when I did client.save(), the saved image still contains the text in the 2nd coordinate.
[
![err3](https://user-images.githubusercontent.com/58328226/194198629-7e0ecccd-dbe9-4a50-afb5-380f1886874c.png)
](url)

**Comment by vsoch** [comment] 2022-10-06 02:26
Did you do `client.clean()` ?

**Comment by NirutaDhimal** [comment] 2022-10-06 03:13
Yes, I did that. First I did client.detect() and then client.clean() and at last I did client.save()

**Comment by vsoch** [comment] 2022-10-06 03:16
I could help to debug but I’d need you to send me a dummy example (an image and recipe) that reproduces the error. Just to confirm - this is a 2D dicom?

perhaps you could take your image, make a copy that replaces identifiers, write all pixels as some single value (e.g the mean across the image) and then we would try to clean and write a different value?

**Comment by NirutaDhimal** [comment] 2022-10-06 04:49
Yes its a 2D dicom file and it has 3 channels. I will send yo the dummy data

**Comment by NirutaDhimal** [comment] 2022-10-06 05:59
@vsoch This link has the dummy data and the deid.dicom file. Please find it.  I have created the dummy file by the process you described above.
[https://drive.google.com/drive/folders/1gwV6UwB44zq042pa6jmwlKZIANvKgTXV?usp=sharing](url)

**Comment by vsoch** [comment] 2022-10-06 06:27
Thank you @NirutaDhimal ! It's after midnight here, but I should be able to debug this (and get back to you) later tomorrow. Stay tuned!

**Comment by NirutaDhimal** [comment] 2022-10-08 02:53
@vsoch only one coordinates were removed from the dummy example when I tried it. 
This is my code
![ss1](https://user-images.githubusercontent.com/58328226/194684585-a0bc1c8f-0a2e-4e88-9f64-355eb7a19e4f.png)
and this is the result 
![ss2](https://user-images.githubusercontent.com/58328226/194684605-c7480931-013d-4704-9b26-6f4d86aea260.png)

**Comment by vsoch** [comment] 2022-10-08 02:57
Something is different between what you and I are doing because my results lists has three entries, and yours has one. Make sure you are using the master branch of deid and copying what I did exactly, and with the same file.

**Comment by NirutaDhimal** [comment] 2022-10-08 03:00
I installed deid using pip and I am working on the same file. I try to copy what you exactly did

**Comment by vsoch** [comment] 2022-10-08 03:03
Could it be that I used the default deid.dicom config and it covers the locations? Or should it have covered the top left?

**Comment by NirutaDhimal** [comment] 2022-10-08 03:11
Given your coordinates, it should have covered the top left and top right. Which deid.dicom file did you use? I haven't specified any group for this in the deid.dicom

{'reason': 'and Manufacturer contains GE Modality contains CT ManufacturerModelName contains GE|Stanford SeriesDescription contains Dose or ImageType contains SCREEN SAVE',
   'group': 'graylist',
   'coordinates': [[0, '0,0,512,121']]},
  {'reason': 'and Modality contains CT|MR ImageType contains DERIVED|SECONDARY|SCREEN|SAVE',
   'group': 'blacklist',
   'coordinates': []}]}
Is this by default?

**Comment by vsoch** [comment] 2022-10-08 03:13
Yes! So if the user doesn’t provide a custom recipe, we use this default, which is packaged with deid in the data folder. It seems that the headers in your dicom file triggered some of the default locations, but perhaps we are missing the top right? Should we try adding it? And where did you derive your metadata and coordinates from?

**Comment by NirutaDhimal** [comment] 2022-10-08 03:18
I copied your code and this what I am getting.
![ss3](https://user-images.githubusercontent.com/58328226/194685411-335a6f87-fbe0-49e6-8717-3466fb99dce1.png)
![aa3](https://user-images.githubusercontent.com/58328226/194685417-f61e34f6-ff50-4c06-986f-236cf2c3d655.png)

But I gave the the custom recipe. I used dcmdump on my original dcm file and derived the metadata and for coordinates I used itksnap to get them as there were texts on these coordinates in the original file and I wanted to remove them

**Comment by NirutaDhimal** [comment] 2022-10-08 03:19
It's supposed to remove on top left and top right

**Comment by vsoch** [comment] 2022-10-08 03:33
Ah ok so our viewers are flipped!

What I'm seeing is that:

1. our viewers are flipped (I used the papaya viewer online, and those sections were on the right for me)
2. the default deid.dicom encompasses one of the sections you are interested in, and an additional one you didn't target.
3. the third section coodinates are still missing.

Now that I understand there should be another box on the other side, let me take a look again at the dummy data you sent and see if I can make sense of it. Back in a bit!

**Comment by NirutaDhimal** [comment] 2022-10-08 03:38
ok thanks for helping me

**Comment by NirutaDhimal** [comment] 2022-10-08 04:04
I used weasis viewer.

**Comment by vsoch** [comment] 2022-10-08 04:06
Quick question - how did you derive the second coordinate? The image is 1024 by 1024, and the coordinate format is two mins followed by two maxes, so if you expect it to blank out the top right I would have expected the mins to be smaller than the maxes. What appears to be happening is that you are "selecting" a box of empty pixels.

**Comment by vsoch** [comment] 2022-10-08 04:18
Okay so here is an example where I've adjusted your coordinates. There is probably a better way to describe it, but what I'm doing is shuffling around your coordinates so min values > max values, and extending the box to span your image (and remember my viewer is flipped). Trying to put this into human terms, I changed your recipe to:

```bash
FORMAT dicom

 %filter graylist

LABEL ANNOTATIONS
    contains Modality CT
    + contains ConversionType WSD
    + contains Manufacturer GE
    + contains ImageType MIP
    + contains ManufacturerModelName Revolution 
    + contains SoftwareVersions taix_bj.84.i386
    + contains Rows 1024
    + contains Columns 1024
    coordinates 1,12,227,195
    coordinates 271,9,1024,118 
                      # minr, minc, maxr, maxc
                      # indexed in the data like mask[minc:maxc, minr:maxr]
                      # those values are set to 0 to "blank" them
%header
ADD PatientIdentityRemoved YES
REPLACE PatientID var:id 
REPLACE SOPInstanceUID var:source_id
```
So from the above, if either of the max values is less than a min, that's an index that will silently error (giving you an empty array). So for example, if I adjust your values to the above I get:

![image](https://user-images.githubusercontent.com/814322/194687731-e0d996eb-c926-4b6b-99b9-42e039024cee.png)

So from what I can tell, the issue here is that the coordinate is wrong. So if you derived these on your own, make sure they are in that format I've shown above, and that supplying the values actually produces boxes (the first one did not, the second box was an empty array).

**Comment by NirutaDhimal** [comment] 2022-10-08 04:19
coordinates are in this format (x,y,w,h) right? My second ccordinate is (737, 9, 271, 118) which means the bottom right of the bounding box is has pixel (1108,127) both of which are less than 1024

**Comment by vsoch** [comment] 2022-10-08 04:31
We follow the same convention as CTP: https://mircwiki.rsna.org/index.php?title=The_CTP_DICOM_Pixel_Anonymizer and you can see our original discussion here: https://gist.github.com/vsoch/df6957be12c34e62b21000603f1687e5 and documentation of it here: https://github.com/pydicom/deid/blob/27d46bb8851952fc3c6639d4675e254907085af7/deid/dicom/pixels/detect.py#L271-L282

Pinging @fimafurman and @wetzelj in case I'm missing something - I've been away from imaging a long time and don't trust myself.

**Comment by NirutaDhimal** [comment] 2022-10-08 04:42
I edited the format in which you specified and it worked. 
![ss4](https://user-images.githubusercontent.com/58328226/194688416-a3b3d6c0-ece6-44b6-b187-9fc5f169a9fa.png)
But I followed the CTP convention. It's (x, y, w, h) where w, h is the width and height of the bounding box.
![ss5](https://user-images.githubusercontent.com/58328226/194688711-024fa27b-151a-4a3e-aa8a-9aa1e1e0ab22.png)
Thanks for helping me and giving your time :)

**Comment by vsoch** [comment] 2022-10-08 04:51
Perfect! Let's wait to hear from @wetzelj and @fimafurman  before closing the issue! If we somehow used a modified format (and also CTP coordinates) we will likely want to tweak one or the other. For the time being, if this works correctly use the format we currently have. Thanks @NirutaDhimal !

**Comment by wetzelj** [comment] 2022-10-13 16:15
In taking a look at the original discussion about this in deid, I *think* the coordinates are working as designed (xmin, ymin, xmax, ymax) - this has always been my understanding of how coordinates should be identified.  While we're still on deid v0.2.28, the following recipe:
```
LABEL Testing
  contains Modality CR
  coordinates 0,0,50,50
  coordinates 50,50,100,100
  coordinates 100,100,150,150
  coordinates 150,150,200,200
  coordinates 200,200,250,250
  coordinates 250,250,300,300
  coordinates 300,300,350,350
  coordinates 350,350,400,400
  coordinates 400,400,450,450
  coordinates 450,450,500,500
  coordinates 500,500,550,550
  coordinates 550,550,600,600
  coordinates 600,600,650,650
  coordinates 650,650,700,700
```
Results in the the following image (pixel 0,0 is top left in my viewer):
![image](https://user-images.githubusercontent.com/32198293/195645143-ff006c0d-58ba-4c56-8201-f22d66366d93.png)

This does not seem to match the definition prescribed by CTP.  Following CTP rules, the recipe that should be used for the diagonal line in the image above would be:
```
LABEL Testing
  contains Modality CR
  coordinates 0,0,50,50
  coordinates 50,50,50,50
  coordinates 100,100,50,50
  coordinates 150,150,50,50
  coordinates 200,200,50,50
  coordinates 250,250,50,50
  coordinates 300,300,50,50
  coordinates 350,350,50,50
  coordinates 400,400,50,50
  coordinates 450,450,50,50
  coordinates 500,500,50,50
  coordinates 550,550,50,50
  coordinates 600,600,50,50
  coordinates 650,650,50,50
```

If the intent is that the coordinates definition should match CTP format, then we definitely seem to have a bug.

**Comment by vsoch** [comment] 2022-10-13 17:05
Agree!

So what about if we allow both - we have a "ctp" type of coordinate (that gets read differently) and we maintain the default (to not break people's workflows?) Or do you think it's better to have one standard, and fix up everything we do now to conform to that?

**Comment by wetzelj** [comment] 2022-10-13 17:11
Personally I think a new "ctp" type would be preferred over a "one standard".  To flip from our current pattern to the "ctp" would introduce a subtle breaking change - that I could envision people could miss very easily since it's just a behavior change.  If we did want to force a single standard, I would prefer to introduce ctp as a new type and then, if we really want it, at a later point in time deprecate the "coordinates" method.

**Comment by vsoch** [comment] 2022-10-13 17:13
Gotcha! The trick then will be figuring out which coordinate come from CTP. I can take a first pass at this if y'all are good with this approach.

**Comment by vsoch** [comment] 2022-10-13 23:14
okay please see https://github.com/pydicom/deid/pull/234

**Comment by vsoch** [comment] 2022-11-22 00:53
We just merged the fix that should resolve this - thanks everyone!

**Closed by vsoch** 2022-11-22 00:53 UTC
